using System;
using System.Diagnostics;
using System.Linq;
using Jay.Text;

using var writer = new CSharpCodeBuilder();

int id = 147;

writer.AutoGeneratedHeader()
    .Namespace("Jay.Text")
    .NewLine()
    .WriteLine("public class TestClass")
    .BracketBlock(cl =>
    {
        cl.WriteLine("public TestClass()")
            .BracketBlock(ctor =>
            {
                ctor.WriteLine("Console.WriteLine(\"Hey\");");
            })
            .NewLine()
            .WriteLine("public override int GetHashCode()")
            .BracketBlock(m =>
            {
                m.WriteLine("return 0;");
            });
    });

string code = writer.ToString();

Console.WriteLine(code);

Debugger.Break();

Console.WriteLine("Press Enter to close");
Console.ReadLine();
