using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using Jay.Text.Code;
using Jay.Text.Code.CSharpCodeBuilderExtensions;
using Jay.Text.Extensions;
using Jay.Text.Utilities;

TextWriter console = Console.Out;




using var writer = new CodeBuilder();

int id = 147;

writer.AutoGeneratedHeader()
    .Namespace("Jay.Text")
    .NewLine()
    .AppendLine("public class TestClass")
    .BracketBlock(cl =>
    {
        cl.AppendLine("public TestClass()")
            .BracketBlock(ctor =>
            {
                ctor.AppendLine("Console.WriteLine(\"Hey\");");
            })
            .NewLine()
            .FormatLine($$"""
                public int DoTheThing()
                {
                    return {{id}};
                }
                {{(CBA)(w => w.AppendLine("Do the Bart, Man!"))}}
                """)
            .AppendLine("public override int GetHashCode()")
            .BracketBlock(m =>
            {
                m.AppendLine("return 0;");
            });
    });

string code = writer.ToString();

Console.WriteLine(code);

//
// string testString = """
//
//     Think I'm a genius
//
//     Bend computers to my will  
//
//
//       I just google stuff
//          _    
//     """;
//
// // var splits = TextHelper.SplitRanges(testString, "i", comparison: StringComparison.OrdinalIgnoreCase);
// // var splitsStrings = splits.Select(range => testString.Substring(range.Start, range.Length)).ToList();
//
// StringSplitOptions splitOptions = (StringSplitOptions)3;
// StringComparison stringComparison = StringComparison.Ordinal;
//
// foreach (var text in testString.TextSplit(Environment.NewLine, splitOptions, stringComparison))
// {
//     console.WriteLine($"\"{text.ToString()}\"");
// }
//
// console.WriteLine("-------------");
//
// foreach (var range in testString.RangeSplit(Environment.NewLine, splitOptions, stringComparison))
// {
//     console.WriteLine($"Range: {range}\t\"{testString[range]}\"");
// }

//Debugger.Break();

console.WriteLine("Press Enter to close");

// Wait
Console.ReadLine();
