using System;
using System.Diagnostics;
using Jay.Text;
using Jay.Text.CSharpCodeBuilderExtensions;




using var writer = new CodeBuilder();

int id = 147;

writer.AutoGeneratedHeader()
    .Namespace("Jay.Text")
    .NewLine()
    .WriteLine("public class TestClass")
    .BracketBlock(cl =>
    {
        cl.WriteLine("public TestClass()")
            .BracketBlock(ctor =>
            {
                ctor.WriteLine("Console.WriteLine(\"Hey\");");
            })
            .NewLine()
            .FormatLine($$"""
                public int DoTheThing()
                {
                    return {{id}};
                }
                {{(CBA)(w => w.WriteLine("Do the Bart, Man!"))}}
                """)
            .WriteLine("public override int GetHashCode()")
            .BracketBlock(m =>
            {
                m.WriteLine("return 0;");
            });
    });

string code = writer.ToString();

Console.WriteLine(code);

Debugger.Break();

Console.WriteLine("Press Enter to close");
Console.ReadLine();
